

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" xml:lang="en">
 <head>
        <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
        <meta charset="utf-8">
		<title>Identity theft basics - Annual Credit Report.com.</title>
		<meta name="description">
		<meta name="format-detection" content="telephone=no">
		<link type="text/css" href="/css/cssreset-min.css" rel="stylesheet">
		


		<link type="text/css" href="/css/main.css" rel="stylesheet">
		<link type="text/css" href="/css/jquery.bxslider.css" rel="stylesheet">
		<script type="text/javascript" src="/js/jquery-1.10.1.min.js"></script>
		<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
		
		<script type="text/javascript" src="/js/ui.js"></script>
		

		<script type="text/javascript" src="/js/functions.js"></script>
       	<script type="text/javascript" src="/js/jQuery.browser.mobile.js"></script>
        <script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
      
      
	</head>
	<body>
		<a name="top" id="top"></a>
        <div class="skip"><a href="#mainContent">Skip to main content</a></div>
		<div id="container">
	        


<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<header role="banner">
   <h1 role="presentation"> <img src="/images/logo.png" alt="Annual Credit Report.com The only source for your free credit reports. Authorized by Federal law"></h1>
    <div id="navBar" class="globalMenu" role="navigation" aria-label="main">
    <ul>
      <li><a href="/index.action">Home</a></li>
      <li><a href="/yourRights.action">All about credit reports</a></li>
      <li class="requestCTA"><a href="/requestReport/landingPage.action">Request yours now!</a></li>
      <li><a href="/reviewYourReport.action">What to look for</a></li>
      <li class="selected"><a href="/protectYourIdentity.action">Protect your identity</a></li>
      <li><a href="/generalQuestions.action">Frequently asked questions</a></li>
      <li><a href="/contactUs.action">Contact us</a></li>
    </ul>
    <div class="clear"></div>
  </div>                
</header>		
			<div class="pageContent">
				<div class="leftNav" role="navigation" aria-label="Protect your identity">
						<div class="pullmenu">
 <ul data-menu-name="main"> 
  <li class="selected"> <a href="/protectYourIdentity.action"> <img src="/images/navArrowSelected.png" alt="">&nbsp; Identity theft basics </a> </li> 
  <li> <a href="/securityFreezeBasics.action"> <img src="/images/navArrow.png" alt="">&nbsp; Security freeze basics </a> </li> 
  <li> <a href="/dataBreachBasics.action"> <img src="/images/navArrow.png" alt="">&nbsp; Data breach basics </a> </li> 
 </ul>
</div>
				</div>
            <div class="rightContent" role="main">
            	<a id="mainContent" name="mainContent" tabindex="-1"></a>
               <div>
 <h1 class="globalHeadline">Protect your identity</h1>
 <h2>Identity theft basics</h2>
 <h3 class="important">What is identity theft?</h3>
 <p>Identity theft is when someone uses your personal information without your permission. They may open a credit card account, get a loan, or rent apartments in your name using your personal information. They also might access your bank or retirement accounts. You may not know that identity theft has happened until you see your credit report, are notified when trying to apply for credit, or get called by a debt collector.</p>
 <p>For more information about identity theft, visit the <a href="https://www.consumer.gov/articles/1015-avoiding-identity-theft" target="_blank">Federal Trade Commission's website</a> or the <a href="http://www.consumerfinance.gov/askcfpb/1243/what-identity-theft.html" target="_blank">Consumer Financial Protection Bureau's website.</a></p>
 <h3>How does identity theft happen?</h3>
 <p>Identity theft is a serious crime. Identity thieves steal information in several ways, such as:</p>
 <ul>
  <li>Digging through trash cans and other places to find documents that contain credit card numbers, account numbers, Social Security Numbers and other personal information</li> 
  <li>Retrieving information from lost or discarded computer equipment, mobile phones and PDAs, or wallets</li> 
  <li>Using rogue Radio-Frequency Identification readers; stealing checks, credit cards, debit cards, passports, driver's licenses, Social Security cards; or skimming the information from card readers to create new cards</li> 
  <li>Stealing information from personal computers using malware or spyware</li> 
  <li>Hacking into computer networks and databases to steal large amounts of personal information or infiltrating organizations that store large amounts of valuable information</li> 
  <li>Acting as a trusted organization to obtain personal information and/or financial information through the mail, telephone, text messaging and email</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <h3>What are some common warning signs of identity theft or fraud?</h3>
 <div>
  &nbsp;
 </div>
 <ul>
  <li>Bills that do not arrive as expected</li> 
  <li>Unexpected credit cards or account statements</li> 
  <li>Denials of credit that you did not apply for</li> 
  <li>Calls or letters about purchases you did not make</li> 
  <li>Incorrect information on your credit reports - accounts or addresses you don't recognize or information that is inaccurate</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>The Federal Trade Commission's website has additional information regarding the <a href="https://www.identitytheft.gov/Warning-Signs-of-Identity-Theft" target="_blank">warning signs of identity theft</a>, the Consumer Financial Protection Bureau's website also provides information on <a href="http://www.consumerfinance.gov/askcfpb/1359/how-can-i-spot-identity-theft.html" target="_blank">common identity theft warning signs.</a></p>
 <div>
  &nbsp;
 </div>
 <h3>How can I protect myself from identity theft?</h3>
 <div>
  &nbsp;
 </div>
 <ul>
  <li>Destroy or shred documents that include personal information before disposing of them</li> 
  <li>Password-protect your computer and other devices, and use anti-virus software</li> 
  <li>Use caution when sharing account numbers and personal information online or over the phone</li> 
  <li>Beware of phishing phone calls or emails where criminals ask you to provide your information to them - they can pose as banks, retail businesses or even people you know like family members, friends or coworkers</li> 
  <li>Monitor your credit card accounts and bank statements</li> 
  <li>Always clear your personal information before donating or selling computers and other devices</li> 
  <li>Obtain your free annual credit report and review it for accuracy</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <h3>How does monitoring my credit help protect my identity?</h3>
 <div>
  &nbsp;
 </div>
 <p>Monitoring your credit report is a good way to spot signs of identity theft, such as errors and suspicious activity and accounts or addresses you don't recognize.<br><br>The Consumer Financial Protection Bureau's website provides <a href="http://www.consumerfinance.gov/askcfpb/search?selected_facets=tag_exact%3Acredit+monitoring+service" target="_blank">additional information on monitoring your credit report.</a></p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>What should I do if I think I may be a victim of identity theft?</h3>
 <p>You should place an initial fraud alert on your file as soon as you suspect you might be a victim of identity theft. You may request a fraud alert from each of the credit reporting companies over the internet or by mail.</p>
 <h3 class="important">Online:</h3>
 <ul class="noBullets">
  <li>Equifax - www.equifax.com/CreditReportAssistance</li> 
  <li>Experian - www.experian.com/fraud</li> 
  <li>TransUnion - www.transunion.com/fraud</li>
 </ul>
 <h3 class="important">Mail:</h3>
 <ul class="noBullets">
  <li>Equifax</li> 
  <li>P.O. Box 105139</li> 
  <li>Atlanta, GA 30348-5139</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <ul class="noBullets">
  <li>Experian</li> 
  <li>P.O. Box 2002</li> 
  <li>Allen, TX 75013</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <ul class="noBullets">
  <li>TransUnion</li> 
  <li>P.O. Box 2000</li> 
  <li>Chester, PA 19016</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Here are some other steps you can take:</p>
 <ul>
  <li>Contact the security or fraud departments of each business where an account was opened or charged without your knowledge.</li> 
  <li>Follow up in writing, with copies of supporting documents.</li> 
  <li>Keep copies of documents and records of your conversations about the theft.</li> 
  <li><a href="https://www.identitytheft.gov/Sample-Letters/identity-theft-credit-bureau" target="_blank">Complete an ID Theft Affidavit</a> and include it with your written statement.</li> 
  <li>File a report with law enforcement officials and provide copies to any creditors needing proof of the crime.</li> 
  <li>Report to the creditor the accounts that you know, or believe, have been tampered with or opened fraudulently.</li> 
  <li>Report identity theft to the Consumer Financial Protection Bureau by submitting a complaint. Your complaint helps law enforcement officials across the country in their investigations. Visit the CFPB's website to <a href="https://help.consumerfinance.gov/app/creditreporting/ask" target="_blank">find out more information on submitting an identity theft complaint.</a></li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Visit <a href="https://www.identitytheft.gov/" target="_blank">IdentityTheft.gov</a> to report identity theft to the Federal Trade Commission and get a free personal recovery plan that:</p>
 <div>
  &nbsp;
 </div>
 <ul>
  <li>Walks you through each recovery step</li> 
  <li>Pre-fills letters and forms for you to send to businesses, debt collectors, and others</li> 
  <li>Tracks your progress and adapts to your changing situation.</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>IdentityTheft.gov has information - and recovery plans - for more than 30 types of identity theft, including tax refund fraud and child identity theft.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>What is fraud alert?</h3>
 <p>A fraud alert is used to inform creditors that you may be a victim of fraud. A fraud alert can make it harder for an identity thief to open accounts in your name. The fraud alert requires creditors to verify that you are the person adding new credit accounts or changing limits on existing credit accounts by contacting you at a phone number you have provided.</p>
 <p>There are three types of alerts you can place on your file:</p>
 <ul>
  <li>Initial fraud alert - if suspect that you have become or are about to become a victim of fraud or identity theft (duration 90 days)</li> 
  <li>Extended fraud alert - if you are a victim of fraud or identity theft; requires a copy of the identity theft report (duration 7 years)</li> 
  <li>Active duty military alert - if you are in the military and want to minimize your risk of fraud or identity theft while you are deployed (duration 1 year).</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Contact any one of the credit reporting companies to place a fraud alert. They will share your request with the other credit reporting companies.</p>
 <div>
  &nbsp;
 </div>
 <h3>As a victim of fraud or identity theft, you have the right to:</h3>
 <div>
  &nbsp;
 </div>
 <ul>
  <li>Request the credit reporting company to block information from your credit report that was the result of identity theft. You must provide an identity theft report from a law enforcement agency to request a block</li> 
  <li>Dispute information you believe is incorrect</li> 
  <li>Request a fraud alert be placed on your credit report</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>The Federal Trade Commission's website provides additional information about <a href="https://www.identitytheft.gov/Know-Your-Rights" target="_blank">your rights when recovering from identity theft.</a></p>
 <p>&nbsp;</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>Does placing a fraud alert hurt my credit score?</h3>
 <p>Placing a fraud alert does not affect your credit score. It alerts creditors that you have been a victim of fraud and that they should take extra steps before extending new credit in your name. These extra steps may slow down the approval process for new credit.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
</div>
               <ul id="prevNextList"> 
 <li><a class="disabledLink"><span class="prevLinkDisabled"></span>Previous<span class="visually-hidden">(disabled)</span></a></li> 
 <li><a href="/securityFreezeBasics.action">Next<span class="nextLink"></span></a></li>
</ul>
			</div>
			<div class="clear"></div>
			</div>
			</div>
			



<div class="footer" role="contentinfo">
<div id="footerContentWrapper">
  <div id="footerLeft">
    <ul>
      <li><a href="/aboutThisSite.action">About this site</a></li>
      
      <li><a href="/privacy.action">U.S. Privacy</a></li>
      <li><a href="/security.action">U.S. Security</a></li>
      
      <li><a href="/termsOfUse.action">Terms of use</a></li>
    </ul>
    <div class="clear"></div>
    <p id="copyright">Copyright &copy; 2017 Central Source, LLC</p>
  </div>
  <div id="footerRight">
    <p>Secure Transaction: For your protection,  this website is secured with the highest level of SSL Certificate encryption.</p>
    <div id="verisign">
	<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
    </div>
  </div>
</div>



</div>
	</body>
</html>
