

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" xml:lang="en">
 <head>
        <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
        <meta charset="utf-8">
		<title>Review your credit report - Annual Credit Report.com.</title>
		<meta name="description">
		<meta name="format-detection" content="telephone=no">
		<link type="text/css" href="/css/cssreset-min.css" rel="stylesheet">
		


		<link type="text/css" href="/css/main.css" rel="stylesheet">
		<link type="text/css" href="/css/jquery.bxslider.css" rel="stylesheet">
		<script type="text/javascript" src="/js/jquery-1.10.1.min.js"></script>
		<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
		
		<script type="text/javascript" src="/js/ui.js"></script>
		

		<script type="text/javascript" src="/js/functions.js"></script>
       	<script type="text/javascript" src="/js/jQuery.browser.mobile.js"></script>
        <script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
      
      
	
                    <script type="text/javascript">
                      var w=window;
                      if(w.performance||w.mozPerformance||w.msPerformance||w.webkitPerformance){var d=document,AKSB=AKSB||{};AKSB.q=[];AKSB.mark=function(a,b){AKSB.q.push(["mark",a,b||(new Date).getTime()])};AKSB.measure=function(a,b,c){AKSB.q.push(["measure",a,b,c||(new Date).getTime()])};AKSB.done=function(a){AKSB.q.push(["done",a])};AKSB.mark("firstbyte",(new Date).getTime());AKSB.prof={custid:"240888",ustr:"",originlat:0,clientrtt:60,ghostip:"104.84.150.96",
                      ipv6:false,pct:10,clientip:"130.105.77.74",requestid:"1bc6b789",region:"25990",protocol:"",blver:11,akM:"x",akN:"ae",akTT:"O",akTX:"1",akTI:"1bc6b789",ai:"216250",ra:"",pmgn:"",pmgi:"",pmp:""};
                      (function(a){var b=d.createElement("script");b.async="async";b.src=a;a=d.getElementsByTagName("script");a=a[a.length-1];a.parentNode.insertBefore(b,a)})(("https:"===d.location.protocol?"https:":"http:")+"//ds-aksb-a.akamaihd.net/aksb.min.js")};
                    </script>
                    </head>
	<body>
		<a name="top" id="top"></a>
        <div class="skip"><a href="#mainContent">Skip to main content</a></div>
		<div id="container">
	        


<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<header role="banner">
   <h1 role="presentation"> <img src="/images/logo.png" alt="Annual Credit Report.com The only source for your free credit reports. Authorized by Federal law"></h1>
    <div id="navBar" class="globalMenu" role="navigation" aria-label="main">
    <ul>
      <li><a href="/index.action">Home</a></li>
      <li><a href="/yourRights.action">All about credit reports</a></li>
      <li class="requestCTA"><a href="/requestReport/landingPage.action">Request yours now!</a></li>
      <li class="selected"><a href="/reviewYourReport.action">What to look for</a></li>
      <li><a href="/protectYourIdentity.action">Protect your identity</a></li>
      <li><a href="/generalQuestions.action">Frequently asked questions</a></li>
      <li><a href="/contactUs.action">Contact us</a></li>
    </ul>
    <div class="clear"></div>
  </div>                
</header>		
			<div class="pageContent">
				<div class="leftNav" role="navigation" aria-label="Review Your Report">
						<div class="pullmenu">
 <ul data-menu-name="main"> 
  <li class="selected"> <a href="/reviewYourReport.action"> <img src="/images/navArrowSelected.png" alt="">&nbsp; Review your credit report </a> </li> 
  <li> <a href="/filingADispute.action"> <img src="/images/navArrow.png" alt="">&nbsp; Filing a dispute </a> </li> 
  <li> <a href="/inaccuraciesInReporting.action"> <img src="/images/navArrow.png" alt="">&nbsp; Inaccuracies in reporting </a> </li> 
 </ul>
</div>
				</div>
            <div class="rightContent" role="main">
            	<a id="mainContent" name="mainContent" tabindex="-1"></a>
               <div>
 <h1>What to look for</h1>
 <h2>Review your credit report</h2>
 <h3>What should I look for when I review my credit report?</h3>
 <p>Make sure that you recognize the information on your credit report including your personally identifiable information, such as names, addresses, Social Security Number, accounts and loans. Then check that the other information on your credit report is accurate and complete. If you find information that you believe does not belong to you or is not correct, contact the business that issued the account or the credit reporting company that issued the report.</p>
 <p>The Consumer Financial Protection Bureau's website has <a href="http://www.consumerfinance.gov/askcfpb/313/what-should-i-look-for-in-my-credit-report-what-are-a-few-of-the-common-credit-report-errors.html" target="_blank">additional information on what to look for when reviewing your credit report</a>.</p>
</div>
               <ul id="prevNextList"> 
 <li><a class="disabledLink"><span class="prevLinkDisabled"></span>Previous<span class="visually-hidden">(disabled)</span></a></li> 
 <li><a href="/filingADispute.action">Next<span class="nextLink"></span></a></li>
</ul>
			</div>
			<div class="clear"></div>
			</div>
			</div>
			



<div class="footer" role="contentinfo">
<div id="footerContentWrapper">
  <div id="footerLeft">
    <ul>
      <li><a href="/aboutThisSite.action">About this site</a></li>
      
      <li><a href="/privacy.action">U.S. Privacy</a></li>
      <li><a href="/security.action">U.S. Security</a></li>
      
      <li><a href="/termsOfUse.action">Terms of use</a></li>
    </ul>
    <div class="clear"></div>
    <p id="copyright">Copyright &copy; 2017 Central Source, LLC</p>
  </div>
  <div id="footerRight">
    <p>Secure Transaction: For your protection,  this website is secured with the highest level of SSL Certificate encryption.</p>
    <div id="verisign">
	<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
    </div>
  </div>
</div>



</div>
	</body>
</html>
