

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" xml:lang="en">
 <head>
        <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
        <meta charset="utf-8">
		<title>About this site - Annual Credit Report.com.</title>
		<meta name="description">
		<meta name="format-detection" content="telephone=no">
		<link type="text/css" href="/css/cssreset-min.css" rel="stylesheet">
		


		<link type="text/css" href="/css/main.css" rel="stylesheet">
		<link type="text/css" href="/css/jquery.bxslider.css" rel="stylesheet">
		<script type="text/javascript" src="/js/jquery-1.10.1.min.js"></script>
		<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
		
		<script type="text/javascript" src="/js/ui.js"></script>
		

		<script type="text/javascript" src="/js/functions.js"></script>
       	<script type="text/javascript" src="/js/jQuery.browser.mobile.js"></script>
        <script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
      
      
	</head>
	<body>
		<a name="top" id="top"></a>
        <div class="skip"><a href="#mainContent">Skip to main content</a></div>
		<div id="container">
	        


<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<header role="banner">
   <h1 role="presentation"> <img src="/images/logo.png" alt="Annual Credit Report.com The only source for your free credit reports. Authorized by Federal law"></h1>
    <div id="navBar" class="globalMenu" role="navigation" aria-label="main">
    <ul>
      <li><a href="/index.action">Home</a></li>
      <li><a href="/yourRights.action">All about credit reports</a></li>
      <li class="requestCTA"><a href="/requestReport/landingPage.action">Request yours now!</a></li>
      <li><a href="/reviewYourReport.action">What to look for</a></li>
      <li><a href="/protectYourIdentity.action">Protect your identity</a></li>
      <li><a href="/generalQuestions.action">Frequently asked questions</a></li>
      <li class="selected"><a href="/contactUs.action">Contact us</a></li>
    </ul>
    <div class="clear"></div>
  </div>                
</header>		
			<div class="pageContent">
				<div class="leftNav" role="navigation" aria-label="Contact us">
						<div class="pullmenu">
 <ul data-menu-name="main"> 
  <li> <a href="/contactUs.action"> <img src="/images/navArrow.png" alt="">&nbsp; Contact Us Form </a> </li> 
  <li class="selected"> <a href="/aboutThisSite.action"> <img src="/images/navArrowSelected.png" alt="">&nbsp; About this site </a> </li> 
  <li> <a href="/suspectPhishing.action"> <img src="/images/navArrow.png" alt="">&nbsp; Suspected phishing </a> </li> 
  <li> <a href="/policies.action"> <img src="/images/navArrow.png" alt="">&nbsp; Policies </a> </li> 
  <li> <a href="/security.action"> <img src="/images/navArrow.png" alt="">&nbsp; Security </a> </li> 
  <li> <a href="/privacy.action"> <img src="/images/navArrow.png" alt="">&nbsp; Privacy </a> </li> 
  <li> <a href="/termsOfUse.action"> <img src="/images/navArrow.png" alt="">&nbsp; Terms of use </a> </li> 
 </ul>
</div>
				</div>
            <div class="rightContent" role="main">
            	<a id="mainContent" name="mainContent" tabindex="-1"></a>
               <div>
 <h1>About this site</h1>
 <p>AnnualCreditReport.com is the official site to get your free annual credit reports. This right is guaranteed by Federal law. You can <a href="http://www.consumerfinance.gov/askcfpb/311/how-do-i-get-a-copy-of-my-credit-report.html" target="_blank">verify this is the official site</a> by visiting the CFPB's website.</p>
 <div>
  &nbsp;
 </div>
 <p>Don't be fooled by look-alike sites. You can be sure that you are on the right site if you type www.AnnualCreditReport.com in your browser address line. Don't come to this site by clicking on a link in another site or in an email.</p>
 <div>
  &nbsp;
 </div>
 <div>
  &nbsp;
 </div>
 <p>This site is maintained by Central Source, LLC. Central Source, LLC is sponsored by Equifax, Experian and TransUnion so you have a single site where you can ask for all three of your free credit reports.</p>
 <div>
  &nbsp;
 </div>
 <h2><img alt="Equifax" src="/images/logos/equifax.png"></h2>
 <p><span class="bold">Equifax:</span> Equifax empowers businesses and consumers with information they can trust. A global leader in information solutions, we leverage one of the largest sources of consumer and commercial data, along with advanced analytics and proprietary technology, to create customized insights that enrich both the performance of businesses and the lives of consumers.</p>
 <div>
  &nbsp;
 </div>
 <p>Customers have trusted Equifax for over 100 years to deliver innovative solutions with the highest integrity and reliability. Businesses - large and small - rely on us for consumer and business credit intelligence, portfolio management, fraud detection, decisioning technology, marketing tools, and much more. We empower individual consumers to manage their personal credit information, protect their identity, and maximize their financial well-being.</p>
 <div>
  &nbsp;
 </div>
 <p>Headquartered in Atlanta, Georgia, Equifax Inc. employs approximately 7,000 people in 15 countries through North America, Latin America and Europe. Equifax is a member of Standard &amp; Poor's (S&amp;P) 500® Index. Our common stock is traded on the New York Stock Exchange under the symbol EFX.</p>
 <div>
  &nbsp;
 </div>
 <p>Equifax is a registered trademark of Equifax Inc., Atlanta, Georgia. All rights reserved</p>
 <div>
  &nbsp;
 </div>
 <p>For more information, please visit www.equifax.com.</p>
 <p><a class="returnTop" href="#top">Back&nbsp;to Top</a></p>
 <div>
  &nbsp;
 </div>
 <h2><img alt="Experian" src="/images/logos/experian.png"></h2>
 <p><span class="bold">Experian:</span> Experian is the leading global information services company, providing data and analytical tools to clients around the world. The Group helps businesses to manage credit risk, prevent fraud, target marketing offers and automate decision making. Experian also helps individuals to check their credit report and credit score, and protect against identity theft.</p>
 <div>
  &nbsp;
 </div>
 <p>Experian plc is listed on the London Stock Exchange (EXPN) and is a constituent of the FTSE 100 index. Total revenue for the year ended 31 March 2012 was US$4.5 billion. Experian employs approximately 17,000 people in 44 countries and has its corporate headquarters in Dublin, Ireland, with operational headquarters in Nottingham, UK; California, US; and São Paulo, Brazil.</p>
 <div>
  &nbsp;
 </div>
 <p>For more information, please visit www.experianplc.com.</p>
 <p><a class="returnTop" href="#top">Back&nbsp;to Top</a></p>
 <div>
  &nbsp;
 </div>
 <h2><img alt="TransUnion" src="/images/logos/transunion.png"></h2>
 <p><span class="bold">TransUnion:</span></p>
 <p><span class="bold">Achieve more with TransUnion</span></p>
 <p>TransUnion is a global leader in credit information and information management services. For more than 45 years, we've worked with businesses and consumers to gather, analyze and deliver the critical information needed to build strong economies throughout the world. The result is two-fold:</p>
 <div>
  &nbsp;
 </div>
 <ol class="numberedList">
  <li>Businesses can better manage risk and customer relationships</li> 
  <li>Consumers can better understand and manage credit to achieve their financial goals</li>
 </ol>
 <div>
  &nbsp;
 </div>
 <p>Our dedicated associates provide solutions to approximately 45,000 businesses and approximately 500 million consumers worldwide.</p>
 <div>
  &nbsp;
 </div>
 <p>Learn more about how we create advantages for our customers every day at www.transunion.com.</p>
 <p><a class="returnTop" href="#top">Back&nbsp;to Top</a></p>
 <div>
  &nbsp;
 </div>
 <div class="clear">
  &nbsp;
 </div>
 <div>
  &nbsp;
 </div>
</div>
               <ul id="prevNextList"> 
 <li><a href="/contactUs.action"><span class="prevLink"></span>Previous</a></li> 
 <li><a href="/suspectPhishing.action">Next<span class="nextLink"></span></a></li>
</ul>
			</div>
			<div class="clear"></div>
			</div>
			</div>
			



<div class="footer" role="contentinfo">
<div id="footerContentWrapper">
  <div id="footerLeft">
    <ul>
      <li><a href="/aboutThisSite.action">About this site</a></li>
      
      <li><a href="/privacy.action">U.S. Privacy</a></li>
      <li><a href="/security.action">U.S. Security</a></li>
      
      <li><a href="/termsOfUse.action">Terms of use</a></li>
    </ul>
    <div class="clear"></div>
    <p id="copyright">Copyright &copy; 2017 Central Source, LLC</p>
  </div>
  <div id="footerRight">
    <p>Secure Transaction: For your protection,  this website is secured with the highest level of SSL Certificate encryption.</p>
    <div id="verisign">
	<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
    </div>
  </div>
</div>



</div>
	</body>
</html>
