

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" xml:lang="en">
 <head>
        <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
        <meta charset="utf-8">
		<title>Frequently asked questions - General questions - Annual Credit Report.com.</title>
		<meta name="description">
		<meta name="format-detection" content="telephone=no">
		<link type="text/css" href="/css/cssreset-min.css" rel="stylesheet">
		


		<link type="text/css" href="/css/main.css" rel="stylesheet">
		<link type="text/css" href="/css/jquery.bxslider.css" rel="stylesheet">
		<script type="text/javascript" src="/js/jquery-1.10.1.min.js"></script>
		<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
		
		<script type="text/javascript" src="/js/ui.js"></script>
		

		<script type="text/javascript" src="/js/functions.js"></script>
       	<script type="text/javascript" src="/js/jQuery.browser.mobile.js"></script>
        <script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
      
      
	</head>
	<body>
		<a name="top" id="top"></a>
        <div class="skip"><a href="#mainContent">Skip to main content</a></div>
		<div id="container">
	        


<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<header role="banner">
   <h1 role="presentation"> <img src="/images/logo.png" alt="Annual Credit Report.com The only source for your free credit reports. Authorized by Federal law"></h1>
    <div id="navBar" class="globalMenu" role="navigation" aria-label="main">
    <ul>
      <li><a href="/index.action">Home</a></li>
      <li><a href="/yourRights.action">All about credit reports</a></li>
      <li class="requestCTA"><a href="/requestReport/landingPage.action">Request yours now!</a></li>
      <li><a href="/reviewYourReport.action">What to look for</a></li>
      <li><a href="/protectYourIdentity.action">Protect your identity</a></li>
      <li class="selected"><a href="/generalQuestions.action">Frequently asked questions</a></li>
      <li><a href="/contactUs.action">Contact us</a></li>
    </ul>
    <div class="clear"></div>
  </div>                
</header>		
			<div class="pageContent">
				<div class="leftNav" role="navigation" aria-label="General Questions">
						<div class="pullmenu">
 <ul data-menu-name="main"> 
  <li class="selected"> <a href="/generalQuestions.action"> <img src="/images/navArrowSelected.png" alt="">&nbsp; General Questions </a> </li> 
 </ul>
</div>
				</div>
            <div class="rightContent" role="main">
            	<a id="mainContent" name="mainContent" tabindex="-1"></a>
               <div>
 <h1 class="globalHeadline">Frequently asked questions</h1>
 <h2>General Questions</h2>
 <h3>Where can I find out more about credit, credit reports and scores, repairing my credit scores, and protecting myself against credit fraud and identify theft?</h3>
 <p>The <a href="http://www.consumer.ftc.gov/" target="_blank">Federal Trade Commission's website</a> and the <a href="http://www.consumerfinance.gov/askcfpb" target="_blank">Consumer Financial Protection Bureau's website</a> offer helpful information about credit and other related topics.</p>
 <p><span class="bold">Federal Trade Commission Articles:</span></p>
 <ul>
  <li><a href="http://www.consumer.ftc.gov/articles/0155-free-credit-reports" target="_blank">Free Credit Reports</a></li> 
  <li><a href="https://www.consumer.ftc.gov/articles/0152-credit-scores" target="_blank">Credit Scores</a></li> 
  <li><a href="https://www.consumer.ftc.gov/articles/0058-credit-repair-how-help-yourself" target="_blank">Credit Repair: How to Help Yourself</a></li> 
  <li><a href="http://www.ftc.gov/idtheft" target="_blank">Identity Theft</a></li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p><span class="bold">Consumer Financial Protection Bureau Topics:</span></p>
 <ul>
  <li><a href="http://www.consumerfinance.gov/askcfpb/search/?selected_facets=category_exact:credit-reporting" target="_blank">Credit Reporting</a></li> 
  <li><a href="http://www.consumerfinance.gov/askcfpb/318/how-do-i-get-and-keep-a-good-credit-score.html" target="_blank">Keeping a Good Credit Score</a></li> 
  <li><a href="http://www.consumerfinance.gov/askcfpb/search/?selected_facets=tag_exact%3Aidentity+theft" target="_blank">Identity Theft</a></li>
 </ul>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>What should I do if I think someone is using my personal information?</h3>
 <p>Visit <a href="https://identitytheft.gov/" target="_blank">IdentityTheft.gov</a> to report identity theft and get a personal recovery plan that will:</p>
 <ul>
  <li>Walk you through each recovery step</li> 
  <li>Pre-fill letters and forms for you to send to businesses, debt collectors, and others</li> 
  <li>Track your progress and adapts to your changing situation.</li>
 </ul>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>Is it safe to provide my Social Security Number to AnnualCreditReport.com?</h3>
 <p>Yes. The site's security protocols and measures protect the personal information you provide. You must enter your Social Security Number to receive a free credit report through AnnualCreditReport.com.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>Why do I need to type characters from a picture before I give you my personal information?</h3>
 <p>Typing the characters from a picture helps ensure that a person - not an automated program - is completing the form. This step helps prevent anyone else from downloading your personal information.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>Can I use my Individual Taxpayer Identification Number (ITIN) to get my free annual credit reports?</h3>
 <p>Not if you use the AnnualCreditReport.com site. We believe your Social Security Number is the most secure number to use, so our site accepts only that number.<br><br>However, since the ITIN has a similar format, you can use your ITIN if you submit your request to one of the three nationwide consumer credit reporting companies by mail. Once the company receives your request, they will verify your identity using their own procedures.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>How can I submit a suggestion or comment about the Annual Credit Report Request Service or this website?</h3>
 <p>Our <a href="/contactUs.action">Contact Us</a> section tells you how to send suggestions or comments.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>I am having a problem downloading the U.S. Mail Request Form using my Google Chrome browser. What can I do to resolve this?</h3>
 <p>If you are using Google's Chrome Browser to view and use our PDF U.S. Mail Request Form, you should be aware that the Chrome Browser uses Google's PDF Viewer by default, rather than the Adobe Reader application. Our PDF U.S. Mail Request Form may not work as designed in Google's Chrome Browser due to this default setting. Our PDF documents are developed with Adobe software in accordance with Adobe PDF standards. To address this issue, you have two options: You can choose which plug-in you wish to use within Chrome. Adobe Reader handles the PDF document as expected, and can be set as your default PDF viewer in the Browser:</p>
 <div>
  &nbsp;
 </div>
 <p>The following steps assume Adobe Reader has already been installed. If not, please install Adobe Reader by navigating to <a href="http://get.adobe.com/reader/" target="_blank">Adobe Reader</a></p>
 <div>
  &nbsp;
 </div>
 <ul>
  <li>Open Google Chrome.</li> 
  <li>Type about:plugins into the address bar and press ENTER.</li> 
  <li>Find the entry for Chrome PDF Viewer and click Disable.</li> 
  <li>Find the entry for Adobe Acrobat and click Disable.</li> 
  <li>Close Chrome and then reopen it.</li> 
  <li>PDF files should now open properly.</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Alternatively, you may choose to open our PDF U.S. Mail Request Form in another browser. The PDF functionality has been tested and works as expected in the latest version(s) of Internet Explorer, Mozilla Firefox, Safari and Opera.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3>Which browsers and versions are compatible with AnnualCreditReport.com?</h3>
 <p>The following web browsers have been tested for use with this site.</p>
 <ul>
  <li>Internet Explorer 11.0</li> 
  <li>Microsoft Edge 13</li> 
  <li>Mozilla Firefox 48.0</li> 
  <li>Google Chrome 53</li> 
  <li>Safari 9.0</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>If the browser you are using is not listed on the above list, you may not have access to all functions within the website. For comments or questions, please <a href="/contactUs.action">Contact Us</a></p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <div>
  &nbsp;
 </div>
</div>
               
			</div>
			<div class="clear"></div>
			</div>
			</div>
			



<div class="footer" role="contentinfo">
<div id="footerContentWrapper">
  <div id="footerLeft">
    <ul>
      <li><a href="/aboutThisSite.action">About this site</a></li>
      
      <li><a href="/privacy.action">U.S. Privacy</a></li>
      <li><a href="/security.action">U.S. Security</a></li>
      
      <li><a href="/termsOfUse.action">Terms of use</a></li>
    </ul>
    <div class="clear"></div>
    <p id="copyright">Copyright &copy; 2017 Central Source, LLC</p>
  </div>
  <div id="footerRight">
    <p>Secure Transaction: For your protection,  this website is secured with the highest level of SSL Certificate encryption.</p>
    <div id="verisign">
	<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
    </div>
  </div>
</div>



</div>
	</body>
</html>
