

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" xml:lang="en">
 <head>
        <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
        <meta charset="utf-8">
		<title>About this site - Terms of use - Annual Credit Report.com.</title>
		<meta name="description">
		<meta name="format-detection" content="telephone=no">
		<link type="text/css" href="/css/cssreset-min.css" rel="stylesheet">
		


		<link type="text/css" href="/css/main.css" rel="stylesheet">
		<link type="text/css" href="/css/jquery.bxslider.css" rel="stylesheet">
		<script type="text/javascript" src="/js/jquery-1.10.1.min.js"></script>
		<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
		
		<script type="text/javascript" src="/js/ui.js"></script>
		

		<script type="text/javascript" src="/js/functions.js"></script>
       	<script type="text/javascript" src="/js/jQuery.browser.mobile.js"></script>
        <script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
      
      
	
                    <script type="text/javascript">
                      var w=window;
                      if(w.performance||w.mozPerformance||w.msPerformance||w.webkitPerformance){var d=document,AKSB=AKSB||{};AKSB.q=[];AKSB.mark=function(a,b){AKSB.q.push(["mark",a,b||(new Date).getTime()])};AKSB.measure=function(a,b,c){AKSB.q.push(["measure",a,b,c||(new Date).getTime()])};AKSB.done=function(a){AKSB.q.push(["done",a])};AKSB.mark("firstbyte",(new Date).getTime());AKSB.prof={custid:"240888",ustr:"",originlat:0,clientrtt:58,ghostip:"104.84.150.96",
                      ipv6:false,pct:10,clientip:"130.105.77.74",requestid:"1bc6b985",region:"25990",protocol:"",blver:11,akM:"x",akN:"ae",akTT:"O",akTX:"1",akTI:"1bc6b985",ai:"216250",ra:"",pmgn:"",pmgi:"",pmp:""};
                      (function(a){var b=d.createElement("script");b.async="async";b.src=a;a=d.getElementsByTagName("script");a=a[a.length-1];a.parentNode.insertBefore(b,a)})(("https:"===d.location.protocol?"https:":"http:")+"//ds-aksb-a.akamaihd.net/aksb.min.js")};
                    </script>
                    </head>
	<body>
		<a name="top" id="top"></a>
        <div class="skip"><a href="#mainContent">Skip to main content</a></div>
		<div id="container">
	        


<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<header role="banner">
   <h1 role="presentation"> <img src="/images/logo.png" alt="Annual Credit Report.com The only source for your free credit reports. Authorized by Federal law"></h1>
    <div id="navBar" class="globalMenu" role="navigation" aria-label="main">
    <ul>
      <li><a href="/index.action">Home</a></li>
      <li><a href="/yourRights.action">All about credit reports</a></li>
      <li class="requestCTA"><a href="/requestReport/landingPage.action">Request yours now!</a></li>
      <li><a href="/reviewYourReport.action">What to look for</a></li>
      <li><a href="/protectYourIdentity.action">Protect your identity</a></li>
      <li><a href="/generalQuestions.action">Frequently asked questions</a></li>
      <li class="selected"><a href="/contactUs.action">Contact us</a></li>
    </ul>
    <div class="clear"></div>
  </div>                
</header>		
			<div class="pageContent">
				<div class="leftNav" role="navigation" aria-label="Contact us">
						<div class="pullmenu">
 <ul data-menu-name="main"> 
  <li> <a href="/contactUs.action"> <img src="/images/navArrow.png" alt="">&nbsp; Contact Us Form </a> </li> 
  <li> <a href="/aboutThisSite.action"> <img src="/images/navArrow.png" alt="">&nbsp; About this site </a> </li> 
  <li> <a href="/suspectPhishing.action"> <img src="/images/navArrow.png" alt="">&nbsp; Suspected phishing </a> </li> 
  <li> <a href="/policies.action"> <img src="/images/navArrow.png" alt="">&nbsp; Policies </a> </li> 
  <li> <a href="/security.action"> <img src="/images/navArrow.png" alt="">&nbsp; Security </a> </li> 
  <li> <a href="/privacy.action"> <img src="/images/navArrow.png" alt="">&nbsp; Privacy </a> </li> 
  <li class="selected"> <a href="/termsOfUse.action"> <img src="/images/navArrowSelected.png" alt="">&nbsp; Terms of use </a> </li> 
 </ul>
</div>
				</div>
            <div class="rightContent" role="main">
            	<a id="mainContent" name="mainContent" tabindex="-1"></a>
               <div>
 <h1>About this site</h1>
 <h2>Terms of use</h2>
 <p>When you use any page on this site except the home page, you accept the following policies on site use:</p>
 <div>
  &nbsp;
 </div>
 <p>By looking at or using the website, you agree that you have read and understand these policies and that you will follow all laws and regulations that apply to using this site of both the United States and the country from where you are accessing this website. You also promise that the information you provide is accurate and complete. You authorize us (Central Source LLC) to send your information to whichever nationwide credit reporting companies you want a credit report from. We may change or update these policies at any time. Please check this page each time you visit this website for the most current policies.</p>
 <p>&nbsp;</p>
</div>
               <ul id="prevNextList"> 
 <li><a href="/privacy.action"><span class="prevLink"></span>Previous</a></li> 
 <li><a class="disabledLink">Next<span class="visually-hidden">(disabled)</span><span class="nextLinkDisabled"></span></a></li>
</ul>
			</div>
			<div class="clear"></div>
			</div>
			</div>
			



<div class="footer" role="contentinfo">
<div id="footerContentWrapper">
  <div id="footerLeft">
    <ul>
      <li><a href="/aboutThisSite.action">About this site</a></li>
      
      <li><a href="/privacy.action">U.S. Privacy</a></li>
      <li><a href="/security.action">U.S. Security</a></li>
      
      <li><a href="/termsOfUse.action">Terms of use</a></li>
    </ul>
    <div class="clear"></div>
    <p id="copyright">Copyright &copy; 2017 Central Source, LLC</p>
  </div>
  <div id="footerRight">
    <p>Secure Transaction: For your protection,  this website is secured with the highest level of SSL Certificate encryption.</p>
    <div id="verisign">
	<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
    </div>
  </div>
</div>



</div>
	</body>
</html>
