

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" xml:lang="en">
 <head>
        <!-- <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
        <meta charset="utf-8">
		<title>What is a credit report? - Annual Credit Report.com.</title>
		<meta name="description">
		<meta name="format-detection" content="telephone=no">
		<link type="text/css" href="/css/cssreset-min.css" rel="stylesheet">
		


		<link type="text/css" href="/css/main.css" rel="stylesheet">
		<link type="text/css" href="/css/jquery.bxslider.css" rel="stylesheet">
		<script type="text/javascript" src="/js/jquery-1.10.1.min.js"></script>
		<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
		
		<script type="text/javascript" src="/js/ui.js"></script>
		

		<script type="text/javascript" src="/js/functions.js"></script>
       	<script type="text/javascript" src="/js/jQuery.browser.mobile.js"></script>
        <script type="text/javascript" src="/js/jquery.leanModal.min.js"></script>
      
      
	</head>
	<body>
		<a name="top" id="top"></a>
        <div class="skip"><a href="#mainContent">Skip to main content</a></div>
		<div id="container">
	        


<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
<meta http-equiv="PRAGMA" content="NO-CACHE">
<header role="banner">
   <h1 role="presentation"> <img src="/images/logo.png" alt="Annual Credit Report.com The only source for your free credit reports. Authorized by Federal law"></h1>
    <div id="navBar" class="globalMenu" role="navigation" aria-label="main">
    <ul>
      <li><a href="/index.action">Home</a></li>
      <li class="selected"><a href="/yourRights.action">All about credit reports</a></li>
      <li class="requestCTA"><a href="/requestReport/landingPage.action">Request yours now!</a></li>
      <li><a href="/reviewYourReport.action">What to look for</a></li>
      <li><a href="/protectYourIdentity.action">Protect your identity</a></li>
      <li><a href="/generalQuestions.action">Frequently asked questions</a></li>
      <li><a href="/contactUs.action">Contact us</a></li>
    </ul>
    <div class="clear"></div>
  </div>                
</header>		
			<div class="pageContent">
				<div class="leftNav" role="navigation" aria-label="What is Credit Report">
						<div class="pullmenu">
 <ul data-menu-name="main"> 
  <li> <a href="/yourRights.action"> <img src="/images/navArrow.png" alt="">&nbsp; Your rights to your credit reports </a> </li> 
  <li class="selected"> <a href="/whatIsCreditReport.action"> <img src="/images/navArrowSelected.png" alt="">&nbsp; What is a credit report? </a> </li> 
  <li> <a href="/gettingReports.action"> <img src="/images/navArrow.png" alt="">&nbsp; Getting your Credit Reports </a> </li> 
  <li> <a href="/requestingReportsInSpecialSituations.action"> <img src="/images/navArrow.png" alt="">&nbsp; Requesting reports in special situations </a> </li> 
 </ul>
</div>
				</div>
            <div class="rightContent" role="main">
            	<a id="mainContent" name="mainContent" tabindex="-1"></a>
               <div>
 <h1>All about credit reports</h1>
 <h2>What is a credit report?</h2>
 <p>When you make a payment on a credit card or loan, the business that gave you the loan or credit keeps a record of how much and often you pay, as well as the credit limits and loan balances. Those businesses and other sources may report your credit, loan and payment history to one or more credit reporting companies. The credit reporting companies each combine the information they receive about your different credit, loan and payment activities into a credit report. The credit reporting companies prepare credit reports for people in the U.S. Since not all businesses report to all three credit reporting companies, the information on your credit reports may vary.</p>
 <p>A credit report is an organized list of the information related to your credit activity. Credit reports may include:</p>
 <ul>
  <li>A list of businesses that have given you credit or loans</li> 
  <li>The total amount for each loan or credit limit for each credit card</li> 
  <li>How often you paid your credit or loans on time, and the amount you paid</li> 
  <li>Any missed or late payments as well as bad debts</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Credit reports may also include:</p>
 <ul>
  <li>A list of businesses that have obtained your credit report within a certain time period</li> 
  <li>Your current and former names, address(es) and/or employers</li> 
  <li>Any bankruptcies or other public record information</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Under Federal law, you are entitled to receive one free copy of your credit report from each credit reporting company every 12 months. For more information <a href="http://www.consumerfinance.gov/askcfpb/309/what-is-a-credit-report.html" target="_blank">visit the Consumer Financial Protection Bureau's website</a>.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3 class="subheading">What is a credit score?</h3>
 <p>Credit scores are the result of mathematical formulas that use the information in your credit report to calculate a value which suggests how likely you are to pay your bills in the future.</p>
 <p>The credit scores you get from different companies will not be the same. There are a number of reasons for that:</p>
 <ul>
  <li>There are many different formulas used to calculate credit scores. The differences in the formulas may lead to differences in your credit scores.</li> 
  <li>Companies may produce scores that give results on different scales.</li> 
  <li>Businesses don't always report to every credit reporting company, and even when they do, they may send their information on different days. This means that on any given day, the information that one credit reporting company has may differ from the credit activity being reported to another credit reporting company.</li>
 </ul>
 <div>
  &nbsp;
 </div>
 <p>Businesses use credit scores to estimate how likely you are to pay back loans or services. People with higher credit scores may be more likely to pay back their debts. People with lower credit scores may be less likely to pay their debts.<br><br>The Consumer Financial Protection Bureau's website has <a href="http://www.consumerfinance.gov/askcfpb/315/what-is-my-credit-score.html" target="_blank">additional information on credit scores</a>.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3 class="subheading">Why don't my free credit reports include credit scores?</h3>
 <p>Your credit report and your credit score are not the same thing. Your credit report contains information that a credit reporting company has received about you. Your credit score is calculated by plugging the information in your credit report into a credit score formula. You may have multiple credit scores based upon who provided the score, and whether the company providing the score used their own scoring model or used a model available from a third party.</p>
 <p>Federal law gives you the right to ask for a copy of your credit report from each nationwide credit reporting company every year for free. However, the law does not require the credit reporting companies to provide a free credit score.</p>
 <p>The Consumer Financial Protection Bureau's website has <a href="http://www.consumerfinance.gov/askcfpb/6/i-got-my-free-credit-reports-but-they-do-not-include-my-credit-scores-can-i-get-my-credit-score-for-free-too.html" target="_blank">additional information on credit scores</a>.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3 class="subheading">What makes my credit score go up or down?</h3>
 <p>A credit score is based on information in your credit report. Some factors include how much money you owe, how long you've owed it, how many new accounts you have, how often you miss or are late with payments, and what type of credit accounts you have. Changes in any of those factors may cause a score to go up or down.</p>
 <p>The Consumer Financial Protection Bureau's website has additional information on <a href="http://www.consumerfinance.gov/askcfpb/search?selected_facets=tag_exact%3Acredit+score" target="_blank">factors that can affect your credit score</a> and <a href="http://www.consumerfinance.gov/askcfpb/318/how-do-i-get-and-keep-a-good-credit-score.html" target="_blank">how you can maintain a good credit score</a>.</p>
 <p>For more information about how to improve your credit please visit the <a href="http://www.consumerfinance.gov/askcfpb/search?selected_facets=tag_exact%3Acredit+score" target="_blank">Federal Trade Commission's website</a>.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3 class="subheading">How is my credit report affected when my spouse dies?</h3>
 <p>Nothing on your credit report should change when your spouse dies. To confirm that nothing has changed, you should obtain a copy of your credit report to review it for accuracy.</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
 <h3 class="subheading">How should I report that someone has died?</h3>
 <p>When someone dies, a family member or an appropriate person such as an executor should send a notice letter to one of the three credit reporting companies and request that they update the credit record to indicate that the person is deceased. The credit reporting company will then share that information with the other two credit reporting companies so that they can update their records.</p>
 <p>The letter should include the following information about the deceased:</p>
 <ul>
  <li>Legal name</li> 
  <li>Social Security Number</li> 
  <li>Date of birth</li> 
  <li>Date of death</li> 
  <li>Last known address</li> 
  <li>A copy of the death certificate or letters testamentary</li>
 </ul>
 <p>&nbsp;</p>
 <p>The letter should also include information about the spouse or executor, including:</p>
 <ul>
  <li>Their full name</li> 
  <li>Address for sending final confirmation</li>
 </ul>
 <p>&nbsp;</p>
 <p>You may submit the notice letter to any of the credit reporting companies by mail:</p>
 <p>&nbsp;&nbsp;&nbsp; Equifax</p>
 <p>&nbsp;&nbsp;&nbsp; P.O. Box 105139</p>
 <p>&nbsp;&nbsp;&nbsp; Atlanta, GA 30348-5139</p>
 <p>&nbsp;</p>
 <p>&nbsp;&nbsp;&nbsp; Experian</p>
 <p>&nbsp;&nbsp;&nbsp; P.O. Box 2002</p>
 <p>&nbsp;&nbsp;&nbsp; Allen, TX 75013</p>
 <p>&nbsp;</p>
 <p>&nbsp;&nbsp;&nbsp; TransUnion</p>
 <p>&nbsp;&nbsp;&nbsp; P.O. Box 2000</p>
 <p>&nbsp;&nbsp;&nbsp; Chester, PA 19016</p>
 <p class="topLink"><a href="#top">Back to top</a></p>
</div>
               <ul id="prevNextList"> 
 <li><a href="/yourRights.action"><span class="prevLink"></span>Previous</a></li> 
 <li><a href="/gettingReports.action">Next<span class="nextLink"></span></a></li>
</ul>
			</div>
			<div class="clear"></div>
			</div>
			</div>
			



<div class="footer" role="contentinfo">
<div id="footerContentWrapper">
  <div id="footerLeft">
    <ul>
      <li><a href="/aboutThisSite.action">About this site</a></li>
      
      <li><a href="/privacy.action">U.S. Privacy</a></li>
      <li><a href="/security.action">U.S. Security</a></li>
      
      <li><a href="/termsOfUse.action">Terms of use</a></li>
    </ul>
    <div class="clear"></div>
    <p id="copyright">Copyright &copy; 2017 Central Source, LLC</p>
  </div>
  <div id="footerRight">
    <p>Secure Transaction: For your protection,  this website is secured with the highest level of SSL Certificate encryption.</p>
    <div id="verisign">
	<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
    </div>
  </div>
</div>



</div>
	</body>
</html>
